### PR TITLE
chore: improve commitlint experience when not using commitizen

### PR DESCRIPTION
**Pull request by kepek**
## PR Type

[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no API changes)
[ ] Build-related changes
[X] CI-related changes
[ ] Documentation content changes
[ ] Application / infrastructure changes
[x] Other: Commit Linter

## What Is the Current Behavior?

It allows committing back changes without type.
```bash
❯ echo "bar" | ./node_modules/.bin/commitlint
```
Issue Number: N/A

## What Is the New Behavior?

It forces the user to specify the "type" of the commit message. 
It will fail if not present or not according to commitizen config.

```bash
❯ echo "bar" | ./node_modules/.bin/commitlint
⧗   input: bar
✖   subject may not be empty [subject-empty]
✖   type may not be empty [type-empty]

✖   found 2 problems, 0 warnings
ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint
```

```bash
❯ echo "foo: bar" | ./node_modules/.bin/commitlint
⧗   input: foo: bar
✖   type must be one of [build, chore, ci, docs, feat, fix, perf, refactor, revert, style, test] [type-enum]

✖   found 1 problems, 0 warnings
ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint
```

## Does this PR Introduce a Breaking Change?

[ ] Yes
[x] No

## Other Information

Useful when using commitlint in CI.

### CODE REVIEW

**Comment by dhhyi** [comment]
@kepek Thank you for the contribution.
It seems to me you are working with an older node version. The currently required is 16.16.0. If you use the provided devcontainer, you are always on the correct one. I took the liberty of updating the `package-lock.json` with the new format.

**Review by dhhyi — APPROVED** [review]

**Comment by kepek** [comment]
@dhhyi you're correct. I haven't used the dev container for this change. I will keep that in mind for the future.

**Comment by jometzner** [comment]
@kepek Can you please rebase with intershop:develop and resolve the conflicts?

**Comment by kepek** [comment]
@jometzner done

**Pull request closed without merging**
