### PR TITLE
perf: main bundle reduction

### PR DESCRIPTION
**Pull request by dhhyi**
## PR Type

[x] Refactoring (no functional changes, no API changes)
[X] Application / infrastructure changes
[x] Other: performance improvement

## What Is the Current Behavior?

- main bundle somehow includes stuff from shared module

## What Is the New Behavior?

- lazy loading done right!

## Does this PR Introduce a Breaking Change?

[ ] Yes
[x] Nay

### CODE REVIEW

**Review by shauke — CHANGES_REQUESTED** [review]
image

I guess the budget configuration needs improvement. You where to effective. 😉

**Comment by shauke** [comment]
The `page` schematics for projects needs adaptions. The generation results in an erroneous routing module.
```
ng g intershop-schematics:page user-question --project organization-management
```
results in
image

**Comment by dhhyi** [comment]
> I guess the budget configuration needs improvement. You where to effective. 😉

budgets adapted 😉

**Comment by dhhyi** [comment]
> The `page` schematics for projects needs adaptions. The generation results in an erroneous routing module.

Should work again. Took some time to find the setting that deactivated the lazy generation. It was hidden in the angular.json.

**Review by shauke — APPROVED** [review]

**Pull request merged**
