### PR TITLE
feat: use new REST API for filters and products on master variation page

### LINKED ISSUE #382: Version varaition attribute filter doesnt work on B2B shop
**Actual Behavior**
There are no variation filter options for version on the AEG pdp 
https://intershoppwa-b2b.azurewebsites.net/Telephones/AEG-ECLIPSE-skuM5012786030527-catnetworks.phones?view=grid

**Expected Behavior**
You should see at least 2 options : 15 / 10
the rest api returns these options

**Steps to Reproduce the Bug**

Go to the PDP of the AEG product
https://intershoppwa-b2b.azurewebsites.net/Telephones/AEG-ECLIPSE-skuM5012786030527-catnetworks.phones?view=grid
Click on the version dropdown box
There are no options in the dropdown box

**Environment Details**

- Desktop: \*

  - OS: linux
  - Browser chrome
  - Project Code Version

### PR DESCRIPTION
**Pull request by dhhyi**
## PR Type

[x] Bugfix
[x] Feature
[x] Refactoring (no functional changes, no API changes)

## What Is the Current Behavior?

- Filters and Products for master variation page in B2B are calculated on the client side.
- Closes #382

## What Is the New Behavior?

New REST API capabilities are used.

http://pwa-gh-review-414-universal-b2b.azurewebsites.net/Telephones/AEG-ECLIPSE-skuM5012786030527-catnetworks.phones?view=grid
http://pwa-gh-review-414-universal-b2b.azurewebsites.net/Microsoft/Microsoft-Surface-Book-2-sku201807231-catComputers.897.897_Microsoft?view=grid
http://pwa-gh-review-414-universal-b2b.azurewebsites.net/Notebooks/Microsoft-Surface-Laptop-sku201807204-catComputers.1835.151?view=grid

## Does this PR Introduce a Breaking Change?

[ ] Yes
[x] No

## Other Information

- new API with minor fixes in next ICM Release (https://jira.intershop.de/browse/IS-31076)
- Required ICM Version: 7.10.25.1-LTS

## TODO:

- [x] replace custom master variation page handling
- [x] replace single returned variation with master for filter selection on product listing pages
- [x] display variation count on master depending on filters
- [x] propagate selected filters for master product from product listing page to master variation page

### CODE REVIEW

**Review by M-Behr — CHANGES_REQUESTED** [review]
- amount of products per option is always displayed as (1)
- not all products are displayed in product list, when using the variation product filters
See my e-mail for more details.

**Review by M-Behr — APPROVED** [review]
The filtering of variations works very well on the list page. I like, that selected filters on the list page are also shown as set on the detail page. The hitcount will be fixed with IS-31450.

**Review by MaxKless — CHANGES_REQUESTED** [review]
Reloading on a category page with variation products leads to missing prices. 
Steps to reproduce: 
- on the b2b demo server, navigate to a category page (tested on http://pwa-gh-review-414-universal-b2b.azurewebsites.net/Notebooks-catComputers.1835.151?view=grid)
- reload the page
- Bug: for both Microsoft Surfaces, the prices are initially loaded correctly before reverting to "N/A - N/A" 
- prices are correctly dispayed on the product page
image

**Review by MaxKless — CHANGES_REQUESTED** [review]
Found a bug when switching languages on the master variation page: 
When you change languages and select the first filter dropdown element, weird things happen (see pictures below)
Steps to reproduce:
-  Go to product master variation page (tested on Microsoft Surface Book 2)
- Switch language to german
- Select the first filter dropdown element 
- The element may be reproduced or wrongly displayed
image

image

This might be related to the following error I get when I navigate to the "Notebook" category page. 
image


 XHRGEThttp://pwa-review.northeurope.cloudapp.azure.com:8081/INTERSHOP/rest/WFS/inSPIRED-inTRONICS_Business-Site/rest;loc=de_DE;cur=EUR/categories/Computers/1835/151/productfilters
[HTTP/1.1 500 Internal Server Error 176ms]

	
GET
	http://pwa-review.northeurope.cloudapp.azure.com:8081/INTERSHOP/rest/WFS/inSPIRED-inTRONICS_Business-Site/rest;loc=de_DE;cur=EUR/categories/Computers/1835/151/productfilters
Status500
Internal Server Error
VersionHTTP/1.1
Transferred567 B (21 B size)

    	
    Accept
    	application/json
    Accept-Encoding
    	gzip, deflate
    Accept-Language
    	en-US,en;q=0.5
    Connection
    	keep-alive
    content-type
    	application/json
    Host
    	pwa-review.northeurope.cloudapp.azure.com:8081
    Origin
    	http://pwa-gh-review-414-universal-b2b.azurewebsites.net
    Referer
    	http://pwa-gh-review-414-universal-b2b.azurewebsites.net/Notebooks-und-PCs-catComputers.1835
    User-Agent
    	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:83.0) Gecko/20100101 Firefox/83.0

**Review by MaxKless — APPROVED** [review]

**Pull request merged**
