### PR TITLE
fix: ngx-meta translate on load is not working

### LINKED ISSUE #69: [QUESTION] SEO locales
I'm currently using the "seo.title.home" in the app-routing-module.ts. 

It's always showing me the "en_US" translation as my title. The weird thing is that I expect to see another translated title here ("nl_NL") since I'm also seeing my other translations perfectly fine in my components while using the translate pipe.

Am I forgetting to set a default language somewhere? Or are the seo related things always looking at "en_US"?

I have defined my own language "nl_NL" inside all my environments as the first locale.

Thank you in advance.

### PR DESCRIPTION
**Pull request by Sebastian-Haehnlein**
## PR Type

- Bugfix

## Issue Number: 
Closes #69

### CODE REVIEW

**Comment by dhhyi** [comment]
I like the approach, but this will just postpone the issue. Locales shall come from the ICM in the distant future. Let's take it agile as it is. :+1:

**Comment by Sebastian-Haehnlein** [comment]
:santa:

**Comment by dhhyi** [comment]
:christmas_tree:

**Comment by dhhyi** [comment]
@nickyhaze this should do it, right?

**Comment by nickyhaze** [comment]
It does! Thank you very much

**Pull request merged**
