### PR TITLE
feat: Punchout User Management for cXML and OCI user

### PR DESCRIPTION
**Pull request by shauke**
Add cXML punchout user management next to OCI punchout user management.
Remove punchout users and roles from the b2b user management.

## ToDos
- [x] fix e2e tests
- [x] ~~punchout user creation with ID only (no first and last name, e.g. for the UI)?~~
      the user name doesn't has to be an email address, that's why we initially leave it as it is

## Does this PR Introduce a Breaking Change?

[x] Yes

BREAKING CHANGES: required Intershop Commerce Management version: 7.10.30.0

## Other Information

Wait for ICM 7.10.30.0

### CODE REVIEW

**Review by shauke — COMMENTED** [review]
These parts probably need further adaptions for the cXML user as well?
https://github.com/intershop/intershop-pwa/blob/develop/projects/organization-management/src/app/store/users/users.selectors.ts#L17-L19
https://github.com/intershop/intershop-pwa/blob/develop/projects/organization-management/src/app/components/user-roles-selection/user-roles-selection.component.ts#L36-L51

**Comment by shauke** [comment]
image
The cXMl Punchout User Management description does not fit.

**Comment by SGrueber** [comment]
We decided to omit the URL hint for the cXML punchout user, because the login process of the cXML user is more complex.

**Review by M-Behr — APPROVED** [review]
Thanks @SGrueber. It looks good. Great job!
I found some missing translations. Perhaps @marschmidt89 can complete them.
screenshot-pwa-gh-review-544-universal-b2b azurewebsites net-2021 04 26-11_10_36

**Review by iwiederhold — APPROVED** [review]

**Review by iwiederhold — DISMISSED** [review]

**Review by M-Behr — DISMISSED** [review]
Perfect! :)

**Review by iwiederhold — DISMISSED** [review]
okay! thx

**Pull request merged**
