### PR TITLE
feat: button for clearing basket

### PR DESCRIPTION
**Pull request by dhhyi**
## PR Type

[x] Feature

Now, that I have seen it in a couple of customer projects, it is time to also have this in the OOTB solution.

## TODO

- [x] Translations
- [ ] Checkbox in ICM BO preferences to make this configurable via `configurations` API
- [ ] IAD (button position? success toasts? ...)

## Does this PR Introduce a Breaking Change?

[ ] Yes
[x] No

## Other Information

[AB#91470](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/91470)

### CODE REVIEW

**Comment by shauke** [comment]
@IAD/UX What do you think can we integrate this "clear cart" functionality on the cart page in this way or do you want to suggest changes to the interaction or the visual design?

image

Please use the deployed demo servers for testing.

**Comment by iwiederhold** [comment]
Maybe the clear button should be not so prominent as the others.
clear_cart_button

**Comment by schadii** [comment]
Please keep the confirmation modal for the clear button. About the placement of the button, please see the following screenshot:
Clear basket (2)

**Review by SGrueber — DISMISSED** [review]

**Review by marschmidt89 — APPROVED** [review]
L10N changes approved.

**Review by shauke — APPROVED** [review]

**Pull request merged**
