### PR TITLE
feat: multi channel deployment with context path support

### PR DESCRIPTION
**Pull request by dhhyi**
## PR Type

[x] Feature
[x] CI-related changes
[x] Documentation content changes
[x] Application / infrastructure changes

## What Is the Current Behavior?

- nginx supports channel selection only via domain.

## What Is the New Behavior?

- nginx supports channel selection via domain and context path

## Does this PR Introduce a Breaking Change?

[x] Yes
[ ] No

## TODO:

- [x] define new format for multi-channel configuration
- [x] refactor channel definition to support domain and context path
- [x] documentation adaption
- [x] test with service worker
- [x] adapt GitLab demo deployment

## Other Information:

- related PR for custom solution already applied in a project: #431 
- redefinition of multi-channel configuration:
  - previous:
  ```
        -e PWA_1_TOPLEVELDOMAIN=net \
        -e PWA_1_CHANNEL=inSPIRED-inTRONICS-Site \
        -e PWA_1_LANG=en_US \
        -e PWA_2_TOPLEVELDOMAIN=de \
        -e PWA_2_CHANNEL=inSPIRED-inTRONICS-Site \
        -e PWA_2_LANG=de_DE \
        -e PWA_3_TOPLEVELDOMAIN=com \
        -e PWA_3_CHANNEL=inSPIRED-inTRONICS_Business-Site \
        -e PWA_3_FEATURES=quoting,recently,compare,businessCustomerRegistration,advancedVariationHandling \
        -e PWA_3_THEME="blue|688dc3" \
        -e PWA_4_TOPLEVELDOMAIN=fr \
        -e PWA_4_LANG=fr_FR \
        -e PWA_4_CHANNEL=inSPIRED-inTRONICS-Site \
        -e PWA_4_APPLICATION=smb-responsive \
        -e PWA_4_FEATURES=quoting \
        -e PWA_4_THEME="blue|688dc3" \
  ```
  - next:
  ```
    CONFIG: |
      .+\.net:
          channel: inSPIRED-inTRONICS-Site
          lang: en_US
      .+\.de:
          channel: inSPIRED-inTRONICS-Site
          lang: de_DE
      .+\.com:
          channel: inSPIRED-inTRONICS_Business-Site
          features: quoting,recently,compare,businessCustomerRegistration,advancedVariationHandling
          theme: "blue|688dc3"
      .+\.fr:
          channel: inSPIRED-inTRONICS-Site
          lang: fr_FR
          application: smb-responsive
          features: quoting
          theme: "blue|688dc3"
  ```
  - context:
  ```
    CONFIG: |
      .+:
          - baseHref: /us
            channel: inSPIRED-inTRONICS-Site
            lang: en_US
          - baseHref: /de
            channel: inSPIRED-inTRONICS_Business-Site
            lang: de_DE
  ```
  - supported by https://github.com/hairyhenderson/gomplate with different sources of data
- Context path routing does not work with service workers, because the cached version of index.html contains a `<base href...` tag, that is cached. Making this work would not be a minimal-invasive implementation. -> documented as known limitation.

### CODE REVIEW

**Review by marschmidt89 — DISMISSED** [review]
Documentation approved, didn't check the other changes.

**Review by MaxKless — CHANGES_REQUESTED** [review]
Logging into the b2b channel causes a 500/Internal Server Error. 

### Steps to reproduce:
- Start the PWA using docker-compose
- Navigate to the homepage (redirected to .../de/home)
- change to the b2b channel at .../us/home
- log in (tested using pmiller)

### Error:
redirected almost instantly to Error page, error 500. The _Home Page_ link redirects to the original channel (in this case b2c from /de). If you refresh the page on /us, the link refers to the correct adress.
Response Headers:
```
HTTP/1.1 500 Internal Server Error
Content-Length: 21
Content-Type: text/plain; charset=utf-8
Accept-Ranges: bytes
Server: Apache/2
X-Powered-By: Express
authentication-token: encryption0@PBEWithMD5AndTripleDES:4HkY09/Wy5o=|tDVYGHJcLDhzU2DxaexRAC2g83xLCeIp5CwUFruKbZyZvK61efXTIlAgEPxYobqu|s6cce3c911f392cea
access-control-expose-headers: error-type,error-missing-attributes,error-invalid-attributes,authentication-token,FieldNames,error-key,location
access-control-allow-origin: *
access-control-allow-methods: GET,POST,PUT,DELETE,HEAD,OPTIONS,PATCH
access-control-allow-headers: authentication-token,UserOrganization,authorization,UserOrganization,authorization,content-type,accept,PreviewContextID
Date: Fri, 23 Oct 2020 08:20:05 GMT
```

**Comment by MaxKless** [comment]
This is obviously setup-dependent but it's somewhat confusing that you can switch the language to french and still be on the \de
baseHref.

**Comment by MaxKless** [comment]
It is possible to be on the /de baseHref but still have the PWA localized in english.

### Steps to reproduce:
- start on the .../us/home page
- navigate to a page that has a route accepted by both channels (tested by proceeding to ../us/checkout/review)
- change channels by replacing "us" with "de" in the URL => land on an empty review page
- remove the trailing part of the url so that only ".../de" remains and hit enter

###Error:
The PWA will load with a .../de baseHref but be localized in english (see image below)


image

**Comment by MaxKless** [comment]
It is possible to be on a ../us baseHref but have the wrong themeing and configuration applied.

### Steps to reproduce:
- start on the .../us/home page
- navigate to an arbitrary route (tested with different products and the register page)
- delete the trailing part of the url so that only "../us" remains and hit enter

### Error:
The PWA will load with orange b2c themeing and configuration (see image below)

image

**Comment by dhhyi** [comment]
resolution to review:
- pmiller has a broken basket on the current public deployment
- URLs `/us/` was not properly rewritten, only `/us` was. This caused the other strange behavior

**Review by MaxKless — CHANGES_REQUESTED** [review]
Not all URLs are correctly rewritten. The "Home Page" link on the **error** page still leads to ".../home" which is redirected to the .../de baseHref, even from the .../us channel.

**Comment by dhhyi** [comment]
> Not all URLs are correctly rewritten. The "Home Page" link on the **error** page still leads to ".../home" which is redirected to the .../de baseHref, even from the .../us channel.

It turned out, I had to add baseHref handling into the `server-html.directive`.
I also found the handling missing for canonical URLs.

Now everything should work -> next round of review 😄

**Review by MaxKless — APPROVED** [review]

**Pull request merged**
