### PR TITLE
feat: product zoom feature

### PR DESCRIPTION
**Pull request by DilaraGueler**
## PR Type

[ ] Bugfix
[X] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no API changes)
[ ] Build-related changes
[ ] CI-related changes
[ ] Documentation content changes
[ ] Application / infrastructure changes
[ ] Other: 

## What Is the Current Behavior?

Product Zoom feature has been added to the Product Detail Page.

## Does this PR Introduce a Breaking Change?

[ ] Yes
[X] No

## Other Information

[AB#82318](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/82318)

### CODE REVIEW

**Review by suschneider — CHANGES_REQUESTED** [review]
- The image that is displayed as the first large image when you open the PDP is missing in the thumbnail images.
- The size of ALL modal dialog is now screen width (see e.g. sign in modal dialog). Only the zoom image dialog should have this special styling. Since special functionality is also needed, it would be better to add a separate component for the zoom dialog.
- Use the styling 'cursor: zoom-in' in case zoom images are available to signal to the user that zooming is possible. And for the next and the previous button area of the image carousel the style 'cursor:pointer' would be nice.

**Review by suschneider — APPROVED** [review]

**Review by iwiederhold — CHANGES_REQUESTED** [review]
Please check the Zoom behavior at a mobile device. The button slips under the browser input and there is no longer an option to close the zoom window. The back action of the browser no longer works either.

**Review by schadii — APPROVED** [review]
Thanks!

**Review by iwiederhold — APPROVED** [review]

**Comment by iwiederhold** [comment]
Please check the Zoom feature at a real mobile device. The previous button in the zoom view has a strange behavior.

**Comment by DilaraGueler** [comment]
> Please check the Zoom feature at a real mobile device. The previous button at the product detail page has a strange behavior after the zoom view.

The back button's behavior will be discussed with another ticket not specifically on product zoom but all modal dialogs in the application.

**Review by shauke — APPROVED** [review]

**Pull request merged**
