### PR TITLE
feat: devcontainer for VSCode

### PR DESCRIPTION
**Pull request by dhhyi**
## PR Type

[x] Feature

## What Is the New Behavior?

- providing a devcontainer with VSCode

## Does this PR Introduce a Breaking Change?

[ ] Yes
[x] No

## Tested on

- [x] Docker for Windows with WSL2 backend
- [x] Ubuntu
- [x] Docker for Windows

## Resources

[VSCode Youtube - A Clean Dev Env, Working Every Time, Everywhere](https://www.youtube.com/watch?v=NNrq2641zTA)
[VSCode Youtube - Remote Development with Visual Studio Code](https://www.youtube.com/watch?v=sakjpegUQsk)

### CODE REVIEW

**Comment by jometzner** [comment]
Hashtag VSCodeDay2021 ? :smiley:

**Comment by jometzner** [comment]
When building the container, step 3 installing the angular/cli is asking for approval to collect anonymous data. Unfortunately there is no keyboard input possible. Did you guys had the same problem?
```
STEP 3: RUN sudo -u node npm install -g @angular/cli
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
/usr/local/share/npm-global/bin/ng -> /usr/local/share/npm-global/lib/node_modules/@angular/cli/bin/ng

> @angular/cli@11.1.2 postinstall /usr/local/share/npm-global/lib/node_modules/@angular/cli
> node ./bin/postinstall/script.js

? Would you like to share anonymous usage data with the Angular Team at Google u
nder
Google’s Privacy Policy at https://policies.google.com/privacy? For more details
 and
how to change this setting, see http://angular.io/analytics. (y/N) 
```

**Comment by dhhyi** [comment]
> node ./bin/postinstall/script.js

@jometzner I added `--ignore-scripts` to the CLI install, which *should* deactivate this. Please try again 😉

**Comment by jometzner** [comment]
> > node ./bin/postinstall/script.js
> 
> @jometzner I added `--ignore-scripts` to the CLI install, which _should_ deactivate this. Please try again

Yes, it works. Thanks Dan!

**Review by shauke — APPROVED** [review]
I provided some documentation "improvements". ;)

**Review by marschmidt89 — APPROVED** [review]

**Pull request merged**
