### PR TITLE
feat: basic auth support for nginx

### PR DESCRIPTION
**Pull request by dhhyi**
## PR Type

[x] Feature

## What Is the Current Behavior?

For Intershop CaaS environments, UAT and INT deployments are configured to use basic auth, so that the shop is not publicly visible or indexed by search engines.
This setup however is performed on the Kubernetes nginx ingress, where it doesn't differentiate between page responses and retrieval of static assets. Some of the assets can not be retrieved by the PWA without setting up cross-origin use-credentials, and even then (with multiple basic auth dialogs popping up), fonts are not properly retrieved.

## What Is the New Behavior?

The PWA nginx container can be set up using basic auth: https://github.com/intershop/intershop-pwa/blob/feat/nginx-basic-auth/docs/guides/nginx-startup.md#basic-auth
Whitelisting IPs is also supported.
The nginx only guards page responses and makes static assets freely available.

## Does this PR Introduce a Breaking Change?

[ ] Yes
[x] No

### CODE REVIEW

**Comment by jometzner** [comment]
We have to discuss this proposal with our operations team.

**Comment by psemdel** [comment]
Hi, it is Maxime, so we discussed with Evident. Danilo will adapt this PR to make it not anymore global but on channel level. With that it would cover the problem of IP restriction at channel level. Some documentation of the concept would be needed then, to make it clear to all future users.

**Comment by dhhyi** [comment]
Hi @psemdel,
Didn't we conclude at leaving this on global level? And specific projects can then adapt this for channel-level? I think this should be the default use case.
I can however have another look at maybe implementing both variants. 😉

**Comment by psemdel** [comment]
Sorry, I may have misunderstood a point. Do as agreed.

**Comment by dhhyi** [comment]
@psemdel I added an opt-out on channel level.
So if only one of three channels should be publicly accessible, then we can define basic auth globally, but again deactivate it in the multi-channel configuration by setting `protected: false` on the channel. (see [documentation](https://github.com/intershop/intershop-pwa/blob/feat/nginx-basic-auth/docs/guides/nginx-startup.md#basic-auth))
I think this should cover our use case 😉

**Review by jometzner — DISMISSED** [review]
All sunshine and happiness

**Review by jometzner — APPROVED** [review]

**Pull request merged**
