### PR TITLE
feat: save language selection as cookie

### LINKED ISSUE #1489: Switch language after accepting cookies
**Actual Behavior**
1. Open https://intershoppwa.azurewebsites.net/home 
2. Switch language to DE
3. Site switched to DE
4. Accept all cookies
5. Site switches to EN

**Expected Behavior**

1. Open https://intershoppwa.azurewebsites.net/home 
2. Switch language to DE
3. Site switched to DE
4. Accept all cookies
5. Site stays on DE

**Steps to Reproduce the Bug**

Take a look at actual behavior

**Environment Details**

- Desktop: \*

  - Browser [Firefox](url)
  - Project Code Version

- Smartphone: \*
  - Browser [e.g. stock browser, safari], Version [e.g. 22]
  - Project Code Version

**Additional Context, like Screenshots, Log File Snippets etc.**

Video of the problem

https://github.com/intershop/intershop-pwa/assets/121181702/4d6540c2-c207-40f7-8f2c-80308ecb7bbe

[AB#88811](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/88811)

### PR DESCRIPTION
**Pull request by SGrueber**
## PR Type

[x] Feature

## What Is the Current Behavior?
The pwa is always opened in the requested language according to the url/default language.

Issue Number: Closes #1489

## What Is the New Behavior?
If the user changes the language the new language is saved as cookie 'preferredLocale' in the browser. The next time he/she opens the pwa the pwa is reloaded in this language if it differs from the current language and this language is supported by the PWA. This cookie is considered as a technically necessary cookie and will be set even if the user only accepts necessary cookies.
This feature is enabled by default and can be disabled by switching the feature toggle 'saveLanguageSelection' off.

## Does this PR Introduce a Breaking Change?

[ ] Yes
[x] No

## Other Information

[AB#86776](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/86776)

### CODE REVIEW

**Comment by Eisie96** [comment]
It doesn't work, when the PWA is running locally with `ng serve` in production mode. The PWA will run into an infinite loop, where the lang parameter has been appended to the existing one. Happens only, when the lang cookie is available

**Comment by SGrueber** [comment]
we are waiting for feedback from a real project before we will merge this pull request

**Comment by Eisie96** [comment]
Please check, when applying the preferred locale, that the locale is available. The problem can occur, when the Multi-Channel configuration contains different channel for different paths.

**Comment by SGrueber** [comment]
add a feature toggle to switch the behavior on/off

**Review by shauke — APPROVED** [review]

**Review by shauke — APPROVED** [review]

**Pull request merged**
