### PR TITLE
DeployDemoServer for non intershop repos

### PR DESCRIPTION
**Pull request by svsaller**
## PR Type

[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no API changes)
[ ] Build-related changes
[ x] CI-related changes
[ ] Documentation content changes
[ ] Application / infrastructure changes
[ ] Other: 

## What Is the Current Behavior?

Issue Number: Closes #

## Does this PR Introduce a Breaking Change?

[ ] Yes
[ ] No

### CODE REVIEW

**Comment by dhhyi** [comment]
I think, this should not be working, as the needed Azure AppService credentials are not shared to forked repositories.

**Comment by svsaller** [comment]
Yes @dhhyi, I had expected that as well. Could this be made available (at least technically) to specific contributors to make the demo server deployment work for them?

**Comment by dhhyi** [comment]
> Could this be made available (at least technically) to specific contributors to make the demo server deployment work for them?

That would mean exposing the docker registry credentials and also the service principal credentials. I think I can safely respond with "NO!" 😄

You can ask for an invite as contributor to the project and commit directly to it instead of your own fork.

Any other thoughts @jometzner @shauke @rkarl-ish ?

**Comment by shauke** [comment]
I found the condition as well but I also read about the GitHub secrets not being shared to the fork pull requests. So as @dhhyi already mentioned this would not solve the problem. So we need to think about inviting the developers as direct contributors or we need to copy branches and pull requests in our repository that need a review server.

**Comment by jometzner** [comment]
It is quite simple:
- You want demo server capabilities in your fork? Please, built a workflow that builds and deploys your artifacts in your environment. 
- You want to use our demo environment? Kindly ask us to become a contributor to this project.

**Pull request closed without merging**
