### PR TITLE
feat: OCI punchout configuration

### PR DESCRIPTION
**Pull request by SGrueber**
## PR Type

[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no API changes)
[ ] Build-related changes
[ ] CI-related changes
[ ] Documentation content changes
[ ] Application / infrastructure changes
[ ] Other: 

## What Is the New Behavior?
There is a new page to configure the OCI punchout.

Formatters are not translated, this will be fixed in the next ICM version.
There is only a client side validation for mapping from/to values. All other validations are done by the server and the response error is shown as error message.

## Does this PR Introduce a Breaking Change?

[ ] Yes
[x] No

## Other Information

[AB#86061](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/86061)

### CODE REVIEW

**Review by iwiederhold — APPROVED** [review]

**Review by schadii — DISMISSED** [review]

**Comment by iwiederhold** [comment]
Is it possible to align the button row?
align_button

**Comment by SGrueber** [comment]
Yes. I'll do that

**Comment by iwiederhold** [comment]
THX!

**Review by marschmidt89 — APPROVED** [review]
l10n for DE, EN approved, FR will be checked later.

**Review by Eisie96 — APPROVED** [review]

**Pull request merged**
