### PR TITLE
feat: create cart from order

### PR DESCRIPTION
**Pull request by LucasHengelhaupt**
## PR Type

[x] Feature

## What Is the Current Behavior?

The PWA does not yet handle reordering products from an existing order.

Issue Number: Closes #

## What Is the New Behavior?

The user can add all items from an order to the shopping cart on the order details page. If products from the order are no longer available or out of stock they won't be added to the cart. The items will be added to the current basket, it does not overwrite the items that are already in the basket.

## Does this PR Introduce a Breaking Change?

[x] No

## Other Information

[AB#94519](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/94519)

### CODE REVIEW

**Review by SGrueber — CHANGES_REQUESTED** [review]
Pls add a PR description

**Review by SGrueber — CHANGES_REQUESTED** [review]
move the button below the cost summary according to the IAD (linked at the story in ADO)

**Review by marschmidt89 — DISMISSED** [review]
L10N Review done

**Review by SGrueber — DISMISSED** [review]

**Review by iwiederhold — CHANGES_REQUESTED** [review]
Please check the button naming again. (ORDER AGAIN)

**Review by mglatter — APPROVED** [review]

**Review by SGrueber — APPROVED** [review]

**Pull request merged**
